export { ReactComponent as IcChangeProfileBtn } from "./changeProfileBtn.svg";
export { ReactComponent as IcCheck1 } from "./check1.svg";
export { ReactComponent as IcCheck2 } from "./check2.svg";
export { ReactComponent as IcCloseBtn } from "./closeBtn.svg";
export { ReactComponent as IcEmptyHeart } from "./emptyHeart.svg";
export { ReactComponent as IcFilterBtn } from "./filterBtn.svg";
export { ReactComponent as IcFullHeart } from "./fullHeart.svg";
export { ReactComponent as IcGrayHeart } from "./grayHeart.svg";
export { ReactComponent as IcHamburger } from "./hamburger.svg";
export { ReactComponent as IcLogo } from "./logo.svg";
export { ReactComponent as IcMenuBarImg } from "./MenuBar Profile.svg";
export { ReactComponent as IcModalCloseBtn } from "./modalCloseBtn.svg";
export { ReactComponent as IcNextCardBtn } from "./nextCardBtn.svg";
export { ReactComponent as IcRightArrow } from "./rightArrow.svg";
export { ReactComponent as IcSmallEmptyHeart } from "./smallEmptyHeart.svg";
export { ReactComponent as IcSmallFullHeart } from "./smallFullHeart.svg";
export { ReactComponent as IcVoteImg1 } from "./voteImg1.svg";
export { ReactComponent as IcVoteImg2 } from "./voteImg2.svg";
