type GtmClassName = {
  [key: string]: string;
  mainPiickleLogo: string;
  mainBestPiickle1: string;
  mainBestPiickle2: string;
  mainBestPiickle3: string;
  mainBestPiickle4: string;
  mainBestPiickle5: string;
  mainMoodPiickleMore: string;
  mainCategory1: string;
  mainCategory2: string;
  mainCategory3: string;
  mainCategory4: string;
  mainCategory5: string;
  mainCategory6: string;
  mainCategory7: string;
  mainCategory8: string;
  mainVote1: string;
  mainVote2: string;
  mainVote3: string;
  mainVote4: string;
  mainCTABtn: string;
  mainMenuBtn: string;
  menuLogin: string;
  menuJoin: string;
  menuRecommendCard: string;
  menuMoodPiickle: string;
  menuMoodPiickleSub: string;
  menuPiickleMe: string;
  menuPiickleMeSub: string;
  cardLike: string;
  cardLogin: string;
  cardJoin: string;
  cardRecommendFilter: string;
  filterClose: string;
  filterMan: string;
  filterWoman: string;
  filterG10: string;
  filterG20: string;
  filterG30: string;
  filterAlone: string;
  filterCouple: string;
  filterFriend: string;
  filterClub: string;
  filter19: string;
  filterDontCare: string;
  filterNew: string;
  filterFriendly: string;
  filterTight: string;
  filterStart: string;
  moodShowCard: string;
  moodIce: string;
  moodCouple: string;
  moodFriend: string;
  moodDeepConversation: string;
  moodIf: string;
  moodBalanceGame: string;
  moodDate: string;
  moodSOPT: string;
  piicleMe1: string;
  piicleMe2: string;
  piicleMe3: string;
  piicleMeVote: string;
  piicleMeLogin: string;
  piicleMeJoin: string;
  piicleMeBack: string;
  piicleMeNext: string;
  piicleMeHome: string;
  joinInfoNext: string;
  joinProfileNext: string;
  joinAcceptComplete: string;
};
export const GTM_CLASS_NAME: GtmClassName = {
  mainPiickleLogo: "click_main_logo",
  mainBestPiickle1: "click_main_best_1",
  mainBestPiickle2: "click_main_best_2",
  mainBestPiickle3: "click_main_best_3",
  mainBestPiickle4: "click_main_best_4",
  mainBestPiickle5: "click_main_best_5",
  mainMoodPiickleMore: "click_main_mood_plus",
  mainCategory1: "click_main_mood_ice",
  mainCategory2: "click_main_mood_couple",
  mainCategory3: "click_main_mood_friend",
  mainCategory4: "click_main_mood_deep",
  mainCategory5: "click_main_mood_if",
  mainCategory6: "click_main_mood_vs",
  mainCategory7: "click_main_mood_date",
  mainCategory8: "click_main_mood_sopt",
  mainVote1: "click_main_vote_1",
  mainVote2: "click_main_vote_2",
  mainVote3: "click_main_vote_3",
  mainVote4: "click_main_vote_4",
  mainCTABtn: "click_main_cta",
  mainMenuBtn: "click_main_menu",
  menuLogin: "click_menu_log",
  menuJoin: "click_menu_joinmember",
  menuRecommendCard: "click_menu_card",
  menuMoodPiickle: "click_menu_mood_main",
  menuMoodPiickleSub: "click_menu_mood_sub",
  menuPiickleMe: "click_menu_vote_main",
  menuPiickleMeSub: "click_menu_vote_sub",
  cardLike: "click_card_like",
  cardLogin: "click_card_log",
  cardJoin: "click_card_joinmember",
  cardRecommendFilter: "click_card_filter",
  filterClose: "click_filter_close",
  filterMan: "click_filter_man",
  filterWoman: "click_filter_woman",
  filterG10: "click_filter_10",
  filterG20: "click_filter_20",
  filterG30: "click_filter_30",
  filterAlone: "click_filter_alone",
  filterCouple: "click_filter_couple",
  filterFriend: "click_filter_friend",
  filterClub: "click_filter_club",
  filter19: "click_filter_19",
  filterDontCare: "click_filter_dontcare",
  filterNew: "click_filter_new",
  filterFriendly: "click_filter_friendly",
  filterTight: "click_filter_tight",
  filterStart: "click_filter_start",
  moodShowCard: "click_mood_bestcard",
  moodIce: "click_mood_ice",
  moodCouple: "click_mood_couple",
  moodFriend: "click_mood_friend",
  moodDeepConversation: "click_mood_deep",
  moodIf: "click_mood_if",
  moodBalanceGame: "click_mood_vs",
  moodDate: "click_mood_date",
  moodSOPT: "click_mood_sopt",
  piicleMe1: "click_vote_1",
  piicleMe2: "click_vote_2",
  piicleMe3: "click_vote_3",
  piicleMeVote: "click_vote_votecompl",
  piicleMeLogin: "click_vote_log",
  piicleMeJoin: "click_vote_joinmember",
  piicleMeBack: "click_vote_back",
  piicleMeNext: "click_vote_next",
  piicleMeHome: "click_vote_gohome",
  joinInfoNext: "click_joinmember_next1",
  joinProfileNext: "click_joinmember_next2",
  joinAcceptComplete: "click_joinmember_compl",
};
