type GtmClassName = {
  [key: string]: string;
  mainPiickleLogo: string;
  mainBannerHot: string;
  mainBannerNew: string;
  mainBannerAddBtn: string;
  mainBannerNotice: string;
  mainTopicRequestBtn: string;
  mainBannerEvent: string;
  mainBestPiickle1: string;
  mainBestPiickle2: string;
  mainBestPiickle3: string;
  mainBestPiickle4: string;
  mainBestPiickle5: string;
  mainBestPiickleMore: string;
  mainMoodPiickleMore: string;
  main아이스브레이킹: string;
  main커플: string;
  main친구: string;
  "main진지한 대화": string;
  mainIF: string;
  main밸런스게임: string;
  main소개팅: string;
  mainSOPT: string;
  mainVote1: string;
  mainVote2: string;
  mainVote3: string;
  mainVote4: string;
  mainCTABtn: string;
  mainMenuBtn: string;
  menuLogin: string;
  menuRecommendCard: string;
  menuMoodPiickle: string;
  menuMoodPiickleSub: string;
  menuPiickleMe: string;
  menuPiickleMeSub: string;
  menuBookmark: string;
  menuOpacityClose: string;
  cardSwipe: string;
  cardBookmark: string;
  cardLogin: string;
  cardJoin: string;
  cardRecommendFilter: string;
  cardMoveBookmark: string;
  cardMoveHome: string;
  cardMoveKeep: string;
  cardMoveCategory: string;
  cardMoveFeedback: string;
  cardShare: string;
  cardEtc: string;
  cardEtcBad: string;
  cardEtcBlock: string;
  cardEtcCancelBlock: string;
  cardEtcWonder: string;
  filterClose: string;
  filter남: string;
  filter여: string;
  filter10대: string;
  filter20대: string;
  filter30대: string;
  filter개인: string;
  filter커플: string;
  filter친구: string;
  filter단체: string;
  filter19금: string;
  filter상관없음: string;
  filter새로워요: string;
  filter친근해요: string;
  filter절친해요: string;
  filterStart: string;
  moodShowCard: string;
  mood아이스브레이킹: string;
  mood커플: string;
  mood친구: string;
  "mood진지한 대화": string;
  moodIF: string;
  mood밸런스게임: string;
  mood소개팅: string;
  moodSOPT: string;
  piickleMeVote: string;
  piickleMeLogin: string;
  piickleMeJoin: string;
  piickleMeBack: string;
  piickleMeNext: string;
  piickleMeHome: string;
  joinInfoNext: string;
  joinProfileNext: string;
  joinAgreeComplete: string;
  medley사랑: string;
  medley애프: string;
  medley여럿: string;
  medley피클: string;
  medley송강: string;
  medleyPreview사랑: string;
  medleyPreview애프: string;
  medleyPreview여럿: string;
  medleyPreview피클: string;
  medleyPreview송강: string;
  medleyPreviewClose사랑: string;
  medleyPreviewClose애프: string;
  medleyPreviewClose여럿: string;
  medleyPreviewClose피클: string;
  medleyPreviewClose송강: string;
  bestBookmark: string;
  bestBookmarkMore: string;
  bestRecentBookmark: string;
  bestRecentBookmarkMore: string;
  bestFemaleBookmark: string;
  bestFemaleBookmarkMore: string;
  bestMaleBookmark: string;
  bestMaleBookmarkMore: string;
};

export const GTM_CLASS_NAME: GtmClassName = {
  mainPiickleLogo: "click_main_logo",
  mainBannerHot: "click_main_hotB",
  mainBannerNew: "click_main_newB",
  mainBannerAddBtn: "click_main_addB1",
  mainBannerNotice: "click_main_notiB",
  mainTopicRequestBtn: "click_main_addB2",
  mainBannerEvent: "click_main_eventnotiB",
  mainBestPiickle1: "click_main_best_1",
  mainBestPiickle2: "click_main_best_2",
  mainBestPiickle3: "click_main_best_3",
  mainBestPiickle4: "click_main_best_4",
  mainBestPiickle5: "click_main_best_5",
  mainBestPiickleMore: "click_main_best_plus",
  mainMoodPiickleMore: "click_main_mood_plus",
  main아이스브레이킹: "click_main_mood_ice",
  main커플: "click_main_mood_couple",
  main친구: "click_main_mood_friend",
  "main진지한 대화": "click_main_mood_deep",
  mainIF: "click_main_mood_if",
  main밸런스게임: "click_main_mood_vs",
  main소개팅: "click_main_mood_date",
  mainSOPT: "click_main_mood_sopt",
  mainVote1: "click_main_vote_1",
  mainVote2: "click_main_vote_2",
  mainVote3: "click_main_vote_3",
  mainVote4: "click_main_vote_4",
  mainCTABtn: "click_main_cta",
  mainMenuBtn: "click_main_menu",
  menuLogin: "click_menu_log",
  menuRecommendCard: "click_menu_card",
  menuMoodPiickle: "click_menu_mood_main",
  menuMoodPiickleSub: "click_menu_mood_sub",
  menuPiickleMe: "click_menu_vote_main",
  menuPiickleMeSub: "click_menu_vote_sub",
  menuBookmark: "click_menu_bookmark",
  menuOpacityClose: "click_menu_opacityclose",
  cardSwipe: "swipe_card_card",
  cardBookmark: "click_card_bookmark",
  cardLogin: "click_card_log",
  cardJoin: "click_card_joinmember",
  cardRecommendFilter: "click_card_filter",
  cardMoveBookmark: "click_card_movebookmark",
  cardMoveHome: "click_card_movehome",
  cardMoveKeep: "click_card_keep",
  cardMoveCategory: "click_card_gocategory",
  cardMoveFeedback: "click_card_feedback",
  cardShare: "click_card_share",
  cardEtc: "click_card_etc",
  cardEtcBad: "click_cardetc_bad",
  cardEtcBlock: "click_cardetc_block",
  cardEtcCancelBlock: "click_cardetc_cancelblock",
  cardEtcWonder: "click_cardetc_wonder",
  filterClose: "click_filter_close",
  filter남: "click_filter_man",
  filter여: "click_filter_woman",
  filter10대: "click_filter_10",
  filter20대: "click_filter_20",
  filter30대: "click_filter_30",
  filter개인: "click_filter_alone",
  filter커플: "click_filter_couple",
  filter친구: "click_filter_friend",
  filter단체: "click_filter_club",
  filter19금: "click_filter_19",
  filter상관없음: "click_filter_dontcare",
  filter새로워요: "click_filter_new",
  filter친근해요: "click_filter_friendly",
  filter절친해요: "click_filter_tight",
  filterStart: "click_filter_start",
  moodShowCard: "click_mood_bestcard",
  mood아이스브레이킹: "click_mood_ice",
  mood커플: "click_mood_couple",
  mood친구: "click_mood_friend",
  "mood진지한 대화": "click_mood_deep",
  moodIF: "click_mood_if",
  mood밸런스게임: "click_mood_vs",
  mood소개팅: "click_mood_date",
  moodSOPT: "click_mood_sopt",
  piickleMeVote: "click_vote_votecompl",
  piickleMeLogin: "click_vote_log",
  piickleMeJoin: "click_vote_joinmember",
  piickleMeBack: "click_vote_back",
  piickleMeNext: "click_vote_next",
  piickleMeHome: "click_vote_gohome",
  joinInfoNext: "click_joinmember_next1",
  joinProfileNext: "click_joinmember_next2",
  joinAgreeComplete: "click_joinmember_compl",
  medley사랑: "click_main_medley_couple",
  medley애프: "click_main_medley_date",
  medley여럿: "click_main_medley_ice",
  medley피클: "click_main_medley_self",
  medley송강: "click_main_medley_vs",
  medleyPreview사랑: "click_couple_preview_start",
  medleyPreview애프: "click_date_preview_start",
  medleyPreview여럿: "click_ice_preview_start",
  medleyPreview피클: "click_self_preview_start",
  medleyPreview송강: "click_vs_preview_start",
  medleyPreviewClose사랑: "click_couple_preview_close",
  medleyPreviewClose애프: "click_date_preview_close",
  medleyPreviewClose여럿: "click_ice_preview_close",
  medleyPreviewClose피클: "click_self_preview_close",
  medleyPreviewClose송강: "click_vs_preview_close",
  bestBookmark: "click_bestcard_bookmark",
  bestBookmarkMore: "click_bestcard_more",
  bestRecentBookmark: "click_recentcard_placed",
  bestRecentBookmarkMore: "click_recentcard_more",
  bestFemaleBookmark: "click_femalecard_placed",
  bestFemaleBookmarkMore: "click_femalecard_more",
  bestMaleBookmark: "click_malecard_placed",
  bestMaleBookmarkMore: "click_malecard_more",
};
